---
title: "Time Series Analysis with forecast package in R"
output: html_notebook
author: The Data Science Show
---

Youtube tutorial [R Markdown](http://rmarkdown.rstudio.com) Notebook. When you  

# Time Series Data
Data that changes over time, e.g., stock price, sales growth.

# AR, MA & ARIMA Models

* Autoregressive (AR) Model

$\gamma_t = \beta_1\gamma_{_t-_1} + \beta_2\gamma_{_t-_2}+...+\beta_\rho\gamma_{_t-_\rho}$

* Moving Average (MA) Model

$\gamma_t = \epsilon_t+\alpha_1\epsilon_{_t-_1}+\alpha_2\epsilon_{_t-_2}+...+\alpha_\delta\epsilon_{_t-_\delta}$
```{r}

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
